# Generated by Django 4.2.20 on 2025-03-31 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
