# Generated by Django 4.2.20 on 2025-04-02 07:43

import apps.recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(max_length=64, validators=[apps.recipes.validators.validate_unit_of_measure]),
        ),
    ]
